### ISSUE TITLE
To run omf install...

### ISSUE THREAD

**Issue by flipswitchingmonkey** [oscpe262/ansible-role-fish#2]
use this:

```
- name: Install theme
  become: true
  become_user: '{{ item }}'
  command: 'fish -c "omf install {{ theme }}"'
  loop: '{{ userlist }}'
```

(note: i'm using a loop for users, not a dict)

**Comment by editedbaseline** [comment]
As an alternative, this also works:

```
- name: "Bob the Fish"
  shell:
    cmd: omf install bobthefish
  args:
    executable: /usr/bin/fish
```

I'm new to Ansible, but stumbled across a [StackOverflow ](https://stackoverflow.com/a/71878606/9294722) post which talked about differences between "command" and "shell"
